Update A.html
ManarOmari/professional-repo pull request #5
Opened 2022-05-24 12:14 UTC by ManarOmari

2022-05-24 12:26 UTC, Mre55 reviewed
**Hi @ManarOmari,**

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :negative_squared_cross_mark:

You have submitted a project, that some linter check is not passing, don't have a pull request description which shows a short summary of what you did in this pull request. 

- [x] Kindly use [this](https://github.com/microverseinc/readme-template/blob/master/README.md) REAMDE template and edit it to your own version.
- [x] Please edit your `a.gitignore` file name to be `.gitignore` which is the proper gitignore file.
- [x] And add `test.md` file and `node_module` to `.gitignore` file.
- [x] Kindly add `.html` and `.css` file with separate commits you can do it by deleting what you have now and add them in separate commit. 



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2022-05-24 12:31 UTC, ManarOmari commented
Dear ,
I have spent 3 hours to understand GitHub and how to add files to .gitignore
And I think it was working fine!!

I will try to update this now .
Thank you

On Tue, May 24, 2022, 15:27 Mihreteab Misganaw ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> *Hi @ManarOmari <https://github.com/ManarOmari>,*
>
> While you made a great effort in this project, unfortunately, I cannot
> proceed to review your code.
> Invalid Code Review Request ❎
>
> You have submitted a project, that some linter check is not passing, don't
> have a pull request description which shows a short summary of what you did
> in this pull request.
>
>    - Kindly use this
>    <https://github.com/microverseinc/readme-template/blob/master/README.md>
>    REAMDE template and edit it to your own version.
>    - Please edit your a.gitignore file name to be .gitignore which is the
>    proper gitignore file.
>    - And add test.md file and node_module to .gitignore file.
>    - Kindly add .html and .css file with separate commits you can do it
>    by deleting what you have now and add them in separate commit.
>
> Your Code Review Request will be marked as invalid in your Dashboard, so
> please submit a new one once you are ready 🙏
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *Invalid Code Review Request Does not count into the code reviews limit.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ManarOmari/professional-repo/pull/5#pullrequestreview-983119672>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIDTEIYYRA725FB2HNXXDQ3VLTDJLANCNFSM5WZLF5JQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-24 13:41 UTC, ManarOmari commented
Dear ,
can you help me ?
should I create new repo and do all things again ?

On Tue, May 24, 2022 at 3:31 PM Manar Alomari ***@***.***>
wrote:

> Dear ,
> I have spent 3 hours to understand GitHub and how to add files to
> .gitignore
> And I think it was working fine!!
>
> I will try to update this now .
> Thank you
>
> On Tue, May 24, 2022, 15:27 Mihreteab Misganaw ***@***.***>
> wrote:
>
>> ***@***.**** commented on this pull request.
>>
>> *Hi @ManarOmari <https://github.com/ManarOmari>,*
>>
>> While you made a great effort in this project, unfortunately, I cannot
>> proceed to review your code.
>> Invalid Code Review Request ❎
>>
>> You have submitted a project, that some linter check is not passing,
>> don't have a pull request description which shows a short summary of what
>> you did in this pull request.
>>
>>    - Kindly use this
>>    <https://github.com/microverseinc/readme-template/blob/master/README.md>
>>    REAMDE template and edit it to your own version.
>>    - Please edit your a.gitignore file name to be .gitignore which is
>>    the proper gitignore file.
>>    - And add test.md file and node_module to .gitignore file.
>>    - Kindly add .html and .css file with separate commits you can do it
>>    by deleting what you have now and add them in separate commit.
>>
>> Your Code Review Request will be marked as invalid in your Dashboard, so
>> please submit a new one once you are ready 🙏
>>
>> Cheers and Happy coding!👏👏👏
>>
>> Feel free to leave any questions or comments in the PR thread if
>> something is not 100% clear.
>> Please, remember to tag me in your question so I can receive the
>> notification.
>>
>> *Please, do not open a new Pull Request for re-reviews. You should use
>> the same Pull Request submitted for the first review, either valid or
>> invalid unless it is requested otherwise.*
>> ------------------------------
>>
>> *Invalid Code Review Request Does not count into the code reviews limit.*
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ManarOmari/professional-repo/pull/5#pullrequestreview-983119672>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AIDTEIYYRA725FB2HNXXDQ3VLTDJLANCNFSM5WZLF5JQ>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2022-05-24 17:42 UTC, Munsa1 requested changes
Hi @ManarOmari, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights


## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly add a description to your pull request. Descriptions explain the changes introduced on a branch Click the three-dotted lines in the image below
![image](https://user-images.githubusercontent.com/81932478/170091584-caab523c-208e-498f-a6f7-e2e8f059f9fc.png)

- [x]  Kindly follow the given template for the readme file. download the readme file template from [this link](https://github.com/microverseinc/readme-templatel) and replace the one you currently have with it. Also, fill out the project name and all the other necessary information such as linked in and github usernames and profile links.

Your readme
![image](https://user-images.githubusercontent.com/81932478/170092379-c6b32e09-3640-4b3f-b82c-d8ae097e1c28.png)

given readme
![image](https://user-images.githubusercontent.com/81932478/170096843-f9c45fc5-f036-480a-a04a-a0a787bd27f0.png)

- [x] Kindly change the file name in the image below to `.gitignore`
![image](https://user-images.githubusercontent.com/81932478/170097293-c5d30c4f-9224-44d4-bed1-011655f8de7d.png)

- [ ]  Add `test.md` file and `node_modules` to .gitignore file.

- [ ]  Add linters, refer to these [instructions](https://github.com/microverseinc/linters-config/tree/master/html-css). Your linters should pass and be green.
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-24 21:18 UTC, ManarOmari commented
I updated all the issues, please look to readMe file

2022-05-24 22:05 UTC, ManarOmari commented
first ,update readme file to fit the template
second , remove a.gitignore file and create .gitignore file and add test.md and other file
third, rename a.html to index.html
finally adding description for this pull request

2022-05-26 16:56 UTC, Ismailco requested changes
### Hi @ManarOmari,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 16:56 UTC, Ismailco commented on .gitignore
> +#.gitignore
- [ ] [Optional] This Pull Request should have a descriptive title telling you what changes are inside, you can change it so it reflects the content of the PR

2022-05-26 16:56 UTC, Ismailco commented on .gitignore
>  test.md
- [ ] Good job adding the ```test.md``` file to the .gitignore, however, you need to remove it from your branch. you can remove ```test.md``` using [this tutorial](https://fedingo.com/how-to-remove-git-ignore-files-from-git-repository/)

2022-05-26 16:56 UTC, Ismailco commented on .gitignore
> +#.gitignore
- [ ] [Optional] This is optional but you can remove unused headers from your README file so it looks more professional,

![Screenshot_20220526_175356](https://user-images.githubusercontent.com/25227022/170536747-fe31dbd4-d3af-42c1-bf57-cbf44a963584.png)

2022-05-31 14:32 UTC, OLIPLICHE approved these changes
Hi @ManarOmari , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 19:24 UTC, merged